[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "bcrypt>=5.0.0",
    "flask>=3.1.2",
    "flask-sqlalchemy>=3.1.1",
    "openpyxl>=3.1.5",
    "sqlalchemy>=2.0.44",
    "werkzeug>=3.1.3",
]
